// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "63eb3505-3281-40b1-a09d-02e07a74a057");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1625514233);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1625513623);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1625513983);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1625514211);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1625513743);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1625514113);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1625256121);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1625514353);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 26466);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1625255994);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c606ca94-2044-4a9a-9650-7174e06ca78d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1625513638601");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1625515446601");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1625513640090");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1625535240090");
user_pref("browser.search.region", "CO");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210531140902");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1625514212");
user_pref("browser.slowStartup.averageTime", 40348);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20210531140902");
user_pref("browser.startup.homepage_override.mstone", "78.11.0");
user_pref("browser.startup.lastColdStartupCheck", 1625514207);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1625256107843");
user_pref("distribution.iniFile.exists.appversion", "78.11.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "2ac898a5123b47cd914cfc54939997f6");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1625514234);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210531140902");
user_pref("extensions.lastAppVersion", "78.11.0");
user_pref("extensions.lastPlatformVersion", "78.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"38662d92-77b9-4a11-a763-b62b494d956a\",\"formautofill@mozilla.org\":\"704308b2-1285-4729-aff1-1d1465f224f3\",\"screenshots@mozilla.org\":\"51b112f2-76a3-4fca-9915-05bb55d4e7bd\",\"webcompat-reporter@mozilla.org\":\"f023acdc-a58c-4a23-89f7-eee0a15e2be6\",\"webcompat@mozilla.org\":\"58203d5a-a657-4a59-8024-ddf96d5c61af\",\"default-theme@mozilla.org\":\"2d992e92-23c8-45c8-816d-3cabaf842ed3\",\"google@search.mozilla.org\":\"506fadc5-4458-4bc8-8393-7b18a71cf3fc\",\"drae@search.mozilla.org\":\"3d3c4f48-f288-4501-8210-3b00d0030ba8\",\"wikipedia@search.mozilla.org\":\"d67ffe86-c137-4259-bd93-d7176c55da9a\",\"bing@search.mozilla.org\":\"829edd81-9f4d-49e5-9a3b-177f025b1f5d\",\"ddg@search.mozilla.org\":\"68b44a95-681d-4d53-86f3-53cdccbac5b6\",\"ebay@search.mozilla.org\":\"2b357a76-be30-4e97-9388-60020f3cbac8\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1625513668);
user_pref("media.gmp-manager.buildID", "20210531140902");
user_pref("media.gmp-manager.lastCheck", 1625513640);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1625281608);
user_pref("places.history.expiration.transient_current_max_pages", 59162);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1625513620);
user_pref("security.remote_settings.intermediates.checked", 1625513620);
user_pref("security.sandbox.content.tempDirSuffix", "7d4a7a79-e000-407f-b043-103c638d568a");
user_pref("security.sandbox.plugin.tempDirSuffix", "5870f70f-ff0b-48ca-895d-8e9a34354155");
user_pref("services.blocklist.addons-mlbf.checked", 1625513620);
user_pref("services.blocklist.gfx.checked", 1625513620);
user_pref("services.blocklist.pinning.checked", 1625513620);
user_pref("services.blocklist.plugins.checked", 1625513620);
user_pref("services.settings.clock_skew_seconds", -1779);
user_pref("services.settings.last_etag", "\"1625510280147\"");
user_pref("services.settings.last_update_seconds", 1625515892);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1625513620);
user_pref("services.settings.main.cfr-fxa.last_check", 1625513620);
user_pref("services.settings.main.cfr.last_check", 1625513620);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1625513620);
user_pref("services.settings.main.hijack-blocklists.last_check", 1625513620);
user_pref("services.settings.main.language-dictionaries.last_check", 1625513620);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1625513620);
user_pref("services.settings.main.public-suffix-list.last_check", 1625513620);
user_pref("services.settings.main.search-config.last_check", 1625513620);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1625513620);
user_pref("services.settings.main.sites-classification.last_check", 1625513620);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1625513620);
user_pref("services.settings.main.whats-new-panel.last_check", 1625513620);
user_pref("services.settings.security.onecrl.checked", 1625513620);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1625281607);
user_pref("toolkit.startup.last_success", 1625514196);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210531140902");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
